# Generated by Django 5.0 on 2023-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_implementosdeportivos_precio_alter_ropa_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementosdeportivos',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropa',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
